export const CHANGE_IMG_TYPES = 'test/CHANGE_IMG_TYPES'
export const CHANGE_IMG_LIST = 'test/CHANGE_IMG_LIST'
export const CHANGE_IS_LOADING = 'test/CHANGE_IS_LOADING'
export const CHANGE_IS_PREVIEW = 'test/CHANGE_IS_PREVIEW'
